//
// GENERATED CODE, DO NOT EDIT THIS FILE!
//
// Generated by ConcreteChoiceGenerator for PendingCancellation.  ISO2002 ID# _waWtryAeEeuyDZ-ukt4YRg.
//

namespace BeneficialStrategies.Iso20022.Choices.InstructionProcessingStatus45Choice;

/// <summary>
/// Cancellation request from yourself for this instruction is pending waiting for further processing.
/// </summary>
public partial record PendingCancellation : IInstructionProcessingStatus45Choice
{
    // Members coming soon...
}
