//
// GENERATED CODE, DO NOT EDIT THIS FILE!
//
// Generated by ConcreteChoiceGenerator for PortfolioTransferNotificationIdentification.  ISO2002 ID# _ts-sSQ34EeKN_Y-2Awiamw.
//

namespace BeneficialStrategies.Iso20022.Choices.References37Choice;

/// <summary>
/// Identification of the portfolio transfer.
/// </summary>
public partial record PortfolioTransferNotificationIdentification : IReferences37Choice
{
    // Members coming soon...
}
