//
// GENERATED CODE, DO NOT EDIT THIS FILE!
//
// Generated by DropdownSourceGenerator for CommissionTypeV2Code.  ISO2002 ID# _bAHcidp-Ed-ak6NoX_4Aeg_-432346988.
//

namespace BeneficialStrategies.Iso20022.Codesets;

/// <summary>
/// Type of service for which the commission is asked or paid.
/// Provides values to be used in dropdown select lists and validation logic.
/// Implements <seealso cref="ICommissionTypeV2CodeDropdownSource"/> by obtaining row data from the metadata contained within the codebase.
/// </summary>
[IsoId("_bAHcidp-Ed-ak6NoX_4Aeg_-432346988")]
public partial class CommissionTypeV2CodeDropdownSource : EnumMetadataManager<CommissionTypeV2Code,ICommissionTypeV2CodeDropdownRow,CommissionTypeV2CodeDropdownRow>
{
    public CommissionTypeV2CodeDropdownSource()
        : base( (enumValue, memberInfo) => new CommissionTypeV2CodeDropdownRow(enumValue, memberInfo))
    {
    }
}
