//
// GENERATED CODE, DO NOT EDIT THIS FILE!
//
// Generated by DropdownSourceGenerator for CommissionValueType1Code.  ISO2002 ID# _bAkIcdp-Ed-ak6NoX_4Aeg_-623760703.
//

namespace BeneficialStrategies.Iso20022.Codesets;

/// <summary>
/// Specifies a type of value of the commission.
/// Provides values to be used in dropdown select lists and validation logic.
/// Implements <seealso cref="ICommissionValueType1CodeDropdownSource"/> by obtaining row data from the metadata contained within the codebase.
/// </summary>
[IsoId("_bAkIcdp-Ed-ak6NoX_4Aeg_-623760703")]
public partial class CommissionValueType1CodeDropdownSource : EnumMetadataManager<CommissionValueType1Code,ICommissionValueType1CodeDropdownRow,CommissionValueType1CodeDropdownRow>
{
    public CommissionValueType1CodeDropdownSource()
        : base( (enumValue, memberInfo) => new CommissionValueType1CodeDropdownRow(enumValue, memberInfo))
    {
    }
}
