//
// GENERATED CODE, DO NOT EDIT THIS FILE!
//
// Generated by DropdownRowGenerator for ExternalSecuritiesPurposeCode.  ISO2002 ID# _5eZzoPomEe2ClqPWkEN24A.
//

using System.Reflection;

namespace BeneficialStrategies.Iso20222.Common;

/// <summary>
/// Specifies the external securities purpose code in the format of character string with a maximum length of 4 characters.
/// The list of valid codes is an external code set published separately.
/// External code sets can be downloaded from www.iso20022.org.
/// Provides values to be used in dropdown select lists and validation logic as instanced by <seealso cref="ExternalSecuritiesPurposeCodeDropdownSource"/>.
/// Implements <seealso cref="IExternalSecuritiesPurposeCodeDropdownRow"/> by obtaining row data from the metadata contained within the codebase.
/// </summary>
[IsoId("_5eZzoPomEe2ClqPWkEN24A")]
public partial class ExternalSecuritiesPurposeCodeDropdownRow : EnumMetadataItem<ExternalSecuritiesPurposeCode>, IExternalSecuritiesPurposeCodeDropdownRow
{
    /// <summary>
    /// Specifies the external securities purpose code in the format of character string with a maximum length of 4 characters.
    /// The list of valid codes is an external code set published separately.
    /// External code sets can be downloaded from www.iso20022.org.
    /// Constructs row state using the specified enum value and reflected values.
    /// </summary>
    /// <param name="value">Enum value for this row.</param>
    /// <param name="memberInfo">Reflected values specific to this row.</param>
    public ExternalSecuritiesPurposeCodeDropdownRow(ExternalSecuritiesPurposeCode value, MemberInfo memberInfo) : base(value, memberInfo)
    {
    }
}
