//
// GENERATED CODE, DO NOT EDIT THIS FILE!
//
// Generated by DropdownSourceGenerator for OptionPayoutType1Code.  ISO2002 ID# _El9IgKbFEeSxuMLA5o46jQ.
//

namespace BeneficialStrategies.Iso20022.Codesets;

/// <summary>
/// Indicates the type of payout that will result from an in-the-money option.
/// Provides values to be used in dropdown select lists and validation logic.
/// Implements <seealso cref="IOptionPayoutType1CodeDropdownSource"/> by obtaining row data from the metadata contained within the codebase.
/// </summary>
[IsoId("_El9IgKbFEeSxuMLA5o46jQ")]
public partial class OptionPayoutType1CodeDropdownSource : EnumMetadataManager<OptionPayoutType1Code,IOptionPayoutType1CodeDropdownRow,OptionPayoutType1CodeDropdownRow>
{
    public OptionPayoutType1CodeDropdownSource()
        : base( (enumValue, memberInfo) => new OptionPayoutType1CodeDropdownRow(enumValue, memberInfo))
    {
    }
}
