//
// GENERATED CODE, DO NOT EDIT THIS FILE!
//
// Generated by DropdownSourceGenerator for RejectionReason38Code.  ISO2002 ID# _2K2fwSwrEeOEV5XHD-BKpw.
//

namespace BeneficialStrategies.Iso20222.Common;

/// <summary>
/// Specifies the reason why the securities financing instruction has a rejected status.
/// Provides values to be used in dropdown select lists and validation logic.
/// Implements <seealso cref="IRejectionReason38CodeDropdownSource"/> by obtaining row data from the metadata contained within the codebase.
/// </summary>
[IsoId("_2K2fwSwrEeOEV5XHD-BKpw")]
public partial class RejectionReason38CodeDropdownSource : EnumMetadataManager<RejectionReason38Code,IRejectionReason38CodeDropdownRow,RejectionReason38CodeDropdownRow>
{
    public RejectionReason38CodeDropdownSource()
        : base( (enumValue, memberInfo) => new RejectionReason38CodeDropdownRow(enumValue, memberInfo))
    {
    }
}
