//
// GENERATED CODE, DO NOT EDIT THIS FILE!
//
// Generated by DropdownRowGenerator for VoteInstruction5Code.  ISO2002 ID# _6Q1QEK4ZEemG7MmivSuE5g.
//

using System.Reflection;

namespace BeneficialStrategies.Iso20022.Codesets;

/// <summary>
/// Specifies a type of voting instruction that can be part of a recommendation to vote.
/// Provides values to be used in dropdown select lists and validation logic as instanced by <seealso cref="VoteInstruction5CodeDropdownSource"/>.
/// Implements <seealso cref="IVoteInstruction5CodeDropdownRow"/> by obtaining row data from the metadata contained within the codebase.
/// </summary>
[IsoId("_6Q1QEK4ZEemG7MmivSuE5g")]
public partial class VoteInstruction5CodeDropdownRow : EnumMetadataItem<VoteInstruction5Code>, IVoteInstruction5CodeDropdownRow
{
    /// <summary>
    /// Specifies a type of voting instruction that can be part of a recommendation to vote.
    /// Constructs row state using the specified enum value and reflected values.
    /// </summary>
    /// <param name="value">Enum value for this row.</param>
    /// <param name="memberInfo">Reflected values specific to this row.</param>
    public VoteInstruction5CodeDropdownRow(VoteInstruction5Code value, MemberInfo memberInfo) : base(value, memberInfo)
    {
    }
}
