//
// GENERATED CODE, DO NOT EDIT THIS FILE!
//
// Generated by MainMessageGenerator for ATMCompletionAcknowledgementV02.  ISO2002 ID# _x3hNsa4TEeWZgJQOa6iKCQ.
//

using System.ComponentModel.DataAnnotations;
using BeneficialStrategies.Iso20022.Components;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using BeneficialStrategies.Iso20022.Choices;
using BeneficialStrategies.Iso20022.ExternalSchema;
using BeneficialStrategies.Iso20022.UserDefined;
using System.Xml;
using System.Xml.Linq;
using Helper = BeneficialStrategies.Iso20022.Framework.IsoXmlSerializationHelper<BeneficialStrategies.Iso20022.catp.ATMCompletionAcknowledgementV02>;

namespace BeneficialStrategies.Iso20022.catp;


/// <summary>
/// This record is an implementation of the catp.009.001.02 ISO standard message type.
/// There are significant differences between different variants of the same message. It is crucial that you select exactly the implementation you intend to send or receive.
/// The ATMCompletionAcknowledgement message is sent by an acquirer or its agent to an ATM to acknowledge the receipt of an ATMCompletionAdvice message.
/// </summary>
[Serializable]
[Description(@"The ATMCompletionAcknowledgement message is sent by an acquirer or its agent to an ATM to acknowledge the receipt of an ATMCompletionAdvice message.")]
public partial record ATMCompletionAcknowledgementV02 : IOuterRecord<ATMCompletionAcknowledgementV02,ATMCompletionAcknowledgementV02Document>
    ,IIsoXmlSerilizable<ATMCompletionAcknowledgementV02>, ISerializeInsideARootElement
{
    
    /// <summary>
    /// The official ISO 20022 designation for this version of this message.
    /// </summary>
    public const string IsoIdentifier = "catp.009.001.02";
    
    /// <summary>
    /// The ISO specified XML tag that should be used for standardized serialization of this message.
    /// </summary>
    public const string XmlTag = "ATMCmpltnAck";
    
    /// <summary>
    /// The XML namespace in which this message is delivered.
    /// </summary>
    public static string IsoXmlNamspace => ATMCompletionAcknowledgementV02Document.DocumentNamespace;
    
    #nullable enable
    /// <summary>
    /// Information related to the protocol management on a segment of the path from the ATM to the acquirer.
    /// </summary>
    [IsoId("_x3hNs64TEeWZgJQOa6iKCQ")]
    [Description(@"Information related to the protocol management on a segment of the path from the ATM to the acquirer.")]
    [DataMember(Name="Hdr")]
    [XmlElement(ElementName="Hdr")]
    [Required]
    public required Header32 Header { get; init; }
    
    /// <summary>
    /// Encrypted body of the message.
    /// </summary>
    [IsoId("_x3hNta4TEeWZgJQOa6iKCQ")]
    [Description(@"Encrypted body of the message.")]
    [DataMember(Name="PrtctdATMCmpltnAck")]
    [XmlElement(ElementName="PrtctdATMCmpltnAck")]
    public ContentInformationType10? ProtectedATMCompletionAcknowledgement { get; init; }
    
    /// <summary>
    /// Information related to the acknowledgement of an ATM completion on the ATM. manager.
    /// </summary>
    [IsoId("_x3hNt64TEeWZgJQOa6iKCQ")]
    [Description(@"Information related to the acknowledgement of an ATM completion on the ATM. manager.")]
    [DataMember(Name="ATMCmpltnAck")]
    [XmlElement(ElementName="ATMCmpltnAck")]
    public ATMCompletionAcknowledgement2? ATMCompletionAcknowledgement { get; init; }
    
    /// <summary>
    /// Trailer of the message containing a MAC.
    /// </summary>
    [IsoId("_x3hNua4TEeWZgJQOa6iKCQ")]
    [Description(@"Trailer of the message containing a MAC.")]
    [DataMember(Name="SctyTrlr")]
    [XmlElement(ElementName="SctyTrlr")]
    public ContentInformationType15? SecurityTrailer { get; init; }
    
    #nullable disable
    
    /// <summary>
    /// Using the state of this record, returns a populated <seealso cref="ATMCompletionAcknowledgementV02Document"/>, usually for the purpose of ISO20022 standard serialization.
    /// </summary>
    public ATMCompletionAcknowledgementV02Document ToDocument()
    {
        return new ATMCompletionAcknowledgementV02Document { Message = this };
    }
    public static XName RootElement => Helper.CreateXName("ATMCmpltnAck");
    
    /// <summary>
    /// Used to format the various primative types during serialization.
    /// </summary>
    public static SerializationFormatter SerializationFormatter { get; set; } = SerializationFormatter.GlobalInstance;
    
    /// <summary>
    /// Serializes the state of this record according to Iso20022 specifications.
    /// </summary>
    public void Serialize(XmlWriter writer, string xmlNamespace)
    {
        writer.WriteStartElement(null, "Hdr", xmlNamespace );
        Header.Serialize(writer, xmlNamespace);
        writer.WriteEndElement();
        if (ProtectedATMCompletionAcknowledgement is ContentInformationType10 ProtectedATMCompletionAcknowledgementValue)
        {
            writer.WriteStartElement(null, "PrtctdATMCmpltnAck", xmlNamespace );
            ProtectedATMCompletionAcknowledgementValue.Serialize(writer, xmlNamespace);
            writer.WriteEndElement();
        }
        if (ATMCompletionAcknowledgement is ATMCompletionAcknowledgement2 ATMCompletionAcknowledgementValue)
        {
            writer.WriteStartElement(null, "ATMCmpltnAck", xmlNamespace );
            ATMCompletionAcknowledgementValue.Serialize(writer, xmlNamespace);
            writer.WriteEndElement();
        }
        if (SecurityTrailer is ContentInformationType15 SecurityTrailerValue)
        {
            writer.WriteStartElement(null, "SctyTrlr", xmlNamespace );
            SecurityTrailerValue.Serialize(writer, xmlNamespace);
            writer.WriteEndElement();
        }
    }
    public static ATMCompletionAcknowledgementV02 Deserialize(XElement element)
    {
        throw new NotImplementedException();
    }
}

/// <summary>
/// This is the outer document that contains the XML serialization wrapper and necessary namespaces for proper serialization.
/// For a more complete description of the business meaning of the message, see the underlying <seealso cref="ATMCompletionAcknowledgementV02"/>.
/// </summary>
[Serializable]
public partial record ATMCompletionAcknowledgementV02Document : IOuterDocument<ATMCompletionAcknowledgementV02>, IXmlSerializable
{
    
    /// <summary>
    /// The ISO specified XML namespace that should be used for standardized serialization of this message type.
    /// </summary>
    public const string DocumentNamespace = "urn:iso:std:iso:20022:tech:xsd:catp.009.001.02";
    
    /// <summary>
    /// The ISO specified XML element name that must surround the inner content to achieve standardized serialization.
    /// </summary>
    public const string DocumentElementName = "Document";
    
    /// <summary>
    /// The instance of <seealso cref="ATMCompletionAcknowledgementV02"/> is required.
    /// </summary>
    [DataMember(Name=ATMCompletionAcknowledgementV02.XmlTag)]
    public required ATMCompletionAcknowledgementV02 Message { get; init; }
    public void WriteXml(XmlWriter writer)
    {
        writer.WriteStartElement(null, DocumentElementName, DocumentNamespace );
        writer.WriteStartElement(ATMCompletionAcknowledgementV02.XmlTag);
        Message.Serialize(writer, DocumentNamespace);
        writer.WriteEndElement();
        writer.WriteEndElement();
        writer.WriteEndDocument();
    }
    
    public void ReadXml(XmlReader reader)
    {
        throw new NotImplementedException();
    }
    
    public System.Xml.Schema.XmlSchema GetSchema() => null;
}
