//
// GENERATED CODE, DO NOT EDIT THIS FILE!
//
// Generated by ConcreteChoiceGenerator for SecuritiesBalanceCustodyReportIdentification.  ISO2002 ID# _9EijQT9mEeCuVfEpWlZb5g.
//

using BeneficialStrategies.Iso20022.Components;
using BeneficialStrategies.Iso20022.ExternalSchema;

namespace BeneficialStrategies.Iso20022.Choices.References18Choice;

/// <summary>
/// Unambiguous identification of the report message to be cancelled.
/// </summary>
public partial record SecuritiesBalanceCustodyReportIdentification : References18Choice_
{
    public required IsoMax35Text Value { get; init; }
}
