//
// GENERATED CODE, DO NOT EDIT THIS FILE!
//
// Generated by ConcreteChoiceGenerator for Cleared.  ISO2002 ID# _i40tkCUMEeeDvf1E8-5blA.
//

namespace BeneficialStrategies.Iso20022.Choices.Cleared4Choice;

/// <summary>
/// Indicates that the contract has been cleared.
/// </summary>
public partial record Cleared : ICleared4Choice
{
    // Members coming soon...
}
