//
// GENERATED CODE, DO NOT EDIT THIS FILE!
//
// Generated by ConcreteChoiceGenerator for AcknowledgedAccepted.  ISO2002 ID# _mbmG6ytVEeyhipY4f42fZQ.
//

namespace BeneficialStrategies.Iso20022.Choices.ProcessingStatus84Choice;

/// <summary>
/// Instruction has been acknowledged by the account servicer.
/// </summary>
public partial record AcknowledgedAccepted : IProcessingStatus84Choice
{
    // Members coming soon...
}
