global using System;
global using System.ComponentModel;
global using System.Collections.Generic;
global using BeneficialStrategies.Iso20022.Metadata;
global using System.Runtime.Serialization;
global using System.Xml.Serialization;
global using BeneficialStrategies.Iso20022.Framework;
global using BeneficialStrategies.Iso20022.Codesets;
global using BeneficialStrategies.Iso20022.Amounts;
