//
// GENERATED CODE, DO NOT EDIT THIS FILE!
//
// Generated by ComponentGenerator for AcceptorCurrencyConversionAdvice2.  ISO2002 ID# _UAtD0dtYEee9e6xduATmQg.
//

using BeneficialStrategies.Iso20022.Choices;
using BeneficialStrategies.Iso20022.ExternalSchema;
using BeneficialStrategies.Iso20022.UserDefined;
using System.Xml;
using System.Xml.Linq;

namespace BeneficialStrategies.Iso20022.Components;

/// <summary>
/// Information related to the currency conversion advice.
/// </summary>
public partial record AcceptorCurrencyConversionAdvice2
     : IIsoXmlSerilizable<AcceptorCurrencyConversionAdvice2>
{
    #nullable enable
    
    /// <summary>
    /// Environment of the transaction.
    /// </summary>
    public required CardPaymentEnvironment69 Environment { get; init; } 
    /// <summary>
    /// Currency conversion of a card payment transaction between an acceptor and a currency conversion provider.
    /// </summary>
    public required CardPaymentTransaction77 Transaction { get; init; } 
    /// <summary>
    /// Result of the currency conversion proposed to the cardholder and its result.
    /// </summary>
    public CurrencyConversion15? CurrencyConversionResult { get; init; } 
    
    #nullable disable
    
    
    /// <summary>
    /// Used to format the various primative types during serialization.
    /// </summary>
    public static SerializationFormatter SerializationFormatter { get; set; } = SerializationFormatter.GlobalInstance;
    
    /// <summary>
    /// Serializes the state of this record according to Iso20022 specifications.
    /// </summary>
    public void Serialize(XmlWriter writer, string xmlNamespace)
    {
        writer.WriteStartElement(null, "Envt", xmlNamespace );
        Environment.Serialize(writer, xmlNamespace);
        writer.WriteEndElement();
        writer.WriteStartElement(null, "Tx", xmlNamespace );
        Transaction.Serialize(writer, xmlNamespace);
        writer.WriteEndElement();
        if (CurrencyConversionResult is CurrencyConversion15 CurrencyConversionResultValue)
        {
            writer.WriteStartElement(null, "CcyConvsRslt", xmlNamespace );
            CurrencyConversionResultValue.Serialize(writer, xmlNamespace);
            writer.WriteEndElement();
        }
    }
    public static AcceptorCurrencyConversionAdvice2 Deserialize(XElement element)
    {
        throw new NotImplementedException();
    }
}
