//
// GENERATED CODE, DO NOT EDIT THIS FILE!
//
// Generated by ComponentGenerator for ATMTransaction27.  ISO2002 ID# _KIj5ca5FEeWCgYcWSNgX5g.
//

namespace BeneficialStrategies.Iso20022.Components;

/// <summary>
/// Transaction for which the exception is sent.
/// </summary>
public partial record ATMTransaction27
{
}
