//
// GENERATED CODE, DO NOT EDIT THIS FILE!
//
// Generated by ComponentGenerator for Baseline5.  ISO2002 ID# _Jxr5cQgHEeSeS5xdjFfOTw.
//

namespace BeneficialStrategies.Iso20022.Components;

/// <summary>
/// Specifies the commercial details of the underlying transaction.
/// </summary>
public partial record Baseline5
{
}
