//
// GENERATED CODE, DO NOT EDIT THIS FILE!
//
// Generated by ComponentGenerator for BlockedHoldingDetails1.  ISO2002 ID# _GdlysxKeEeKj15WxqwlXPw.
//

using BeneficialStrategies.Iso20022.Choices;
using BeneficialStrategies.Iso20022.ExternalSchema;
using BeneficialStrategies.Iso20022.UserDefined;

namespace BeneficialStrategies.Iso20022.Components;

/// <summary>
/// Specifies information about a blocked holding.
/// </summary>
[DataContract]
[XmlType]
public partial record BlockedHoldingDetails1
{
    #nullable enable
    
    /// <summary>
    /// Specifies how the blocked account holding is defined.
    /// </summary>
    [DataMember]
    public required Holding1Code BlockedHolding { get; init; } 
    /// <summary>
    /// When an account is blocked at the level of fund, partially, this is the number of units blocked.
    /// </summary>
    [DataMember]
    public IsoDecimalNumber? PartialHoldingUnits { get; init; } 
    /// <summary>
    /// When an account is blocked at the level of fund, this specifies the certificate number of the blocked units.
    /// </summary>
    [DataMember]
    public IsoMax35Text? HoldingCertificateNumber { get; init; } 
    
    #nullable disable
}
