//
// GENERATED CODE, DO NOT EDIT THIS FILE!
//
// Generated by ComponentGenerator for ClearingExceptionOrExemption2.  ISO2002 ID# _AjSxdZPuEey0rJ3Gl6WZVA.
//

using BeneficialStrategies.Iso20022.Choices;
using BeneficialStrategies.Iso20022.ExternalSchema;
using BeneficialStrategies.Iso20022.UserDefined;

namespace BeneficialStrategies.Iso20022.Components;

/// <summary>
/// Further details on clearing exceptions or exemptions.
/// </summary>
[DataContract]
[XmlType]
public partial record ClearingExceptionOrExemption2
{
    #nullable enable
    
    /// <summary>
    /// Identifies the type of clearing exemption or exception that the reporting counterparty has elected.
    /// </summary>
    [DataMember]
    public required NonClearingReason2 ReportingCounterparty { get; init; } 
    /// <summary>
    /// Identifies the type of clearing exemption or exception that the other counterparty has elected.
    /// </summary>
    [DataMember]
    public NonClearingReason2? OtherCounterparty { get; init; } 
    
    #nullable disable
}
