//
// GENERATED CODE, DO NOT EDIT THIS FILE!
//
// Generated by ComponentGenerator for CommunicationAddress3.  ISO2002 ID# _QKBcuNp-Ed-ak6NoX_4Aeg_-46881250.
//

namespace BeneficialStrategies.Iso20022.Components;

/// <summary>
/// Communication device number or electronic address used for communication.
/// </summary>
public partial record CommunicationAddress3
{
}
