//
// GENERATED CODE, DO NOT EDIT THIS FILE!
//
// Generated by ComponentGenerator for CorporateActionStandingInstructionCancellationRejectionStatus1.  ISO2002 ID# _Rk6tZNp-Ed-ak6NoX_4Aeg_1198444441.
//

namespace BeneficialStrategies.Iso20022.Components;

/// <summary>
/// Provides reason of the rejection of a standing instruction cancellation request.
/// </summary>
public partial record CorporateActionStandingInstructionCancellationRejectionStatus1
{
}
