//
// GENERATED CODE, DO NOT EDIT THIS FILE!
//
// Generated by ComponentGenerator for EnvironmentalCommodityEmission1.  ISO2002 ID# _6msQIw2oEeW72qLtWESimw.
//

using BeneficialStrategies.Iso20022.Choices;
using BeneficialStrategies.Iso20022.ExternalSchema;
using BeneficialStrategies.Iso20022.UserDefined;

namespace BeneficialStrategies.Iso20022.Components;

/// <summary>
/// Defines commodity sub-product attributes of an environmental derivative of type emission.
/// </summary>
[DataContract]
[XmlType]
public partial record EnvironmentalCommodityEmission1
{
    #nullable enable
    
    /// <summary>
    /// Base product for the underlying asset class as specified in the classification of commodities derivatives table.
    /// </summary>
    [DataMember]
    public required AssetClassProductType3Code BaseProduct { get; init; } 
    /// <summary>
    /// Sub-product for the underlying asset class.
    /// </summary>
    [DataMember]
    public required AssetClassSubProductType10Code SubProduct { get; init; } 
    /// <summary>
    /// Further subproduct type related to instruments that have a non-financial instrument or commodity as underlying.
    /// </summary>
    [DataMember]
    public AssetClassDetailedSubProductType8Code? AdditionalSubProduct { get; init; } 
    
    #nullable disable
}
