//
// GENERATED CODE, DO NOT EDIT THIS FILE!
//
// Generated by ComponentGenerator for IsabelSignatureHash1.  ISO2002 ID# _c4XEYKA3EeWiJt5KdX5iuQ.
//

using BeneficialStrategies.Iso20022.Choices;

namespace BeneficialStrategies.Iso20022.Components;

/// <summary>
/// Specifies the hash data for the file signature.
/// </summary>
public partial record IsabelSignatureHash1
{
    #nullable enable
    
    /// <summary>
    /// Arbitrary block of data defined as a fixed-size bit string, the (cryptographic) hash value, that allows the detection of an accidental or intentional change to the data.
    /// </summary>
    public required IsoMax50Binary Hash { get; init; } 
    /// <summary>
    /// Effective method for calculating the signature hash using a finite sequence of instructions.
    /// </summary>
    public required IsoMax105Text Algorithm { get; init; } 
    
    #nullable disable
}
