//
// GENERATED CODE, DO NOT EDIT THIS FILE!
//
// Generated by ComponentGenerator for MessageReference2.  ISO2002 ID# _q3e2gQ1ZEeiuP6VVHwBG8A.
//

namespace BeneficialStrategies.Iso20022.Components;

/// <summary>
/// Message reference of relevance to the present message.
/// </summary>
public partial record MessageReference2
{
}
