//
// GENERATED CODE, DO NOT EDIT THIS FILE!
//
// Generated by ComponentGenerator for NameAndAddress9.  ISO2002 ID# _PbrI9dp-Ed-ak6NoX_4Aeg_290283595.
//

namespace BeneficialStrategies.Iso20022.Components;

/// <summary>
/// Information that locates and identifies a party.
/// </summary>
public partial record NameAndAddress9
{
}
