//
// GENERATED CODE, DO NOT EDIT THIS FILE!
//
// Generated by ComponentGenerator for OriginalTransactionAmount2.  ISO2002 ID# _K-cTUZF0EeukDPgU2BMkjQ.
//

using BeneficialStrategies.Iso20022.Choices;

namespace BeneficialStrategies.Iso20022.Components;

/// <summary>
/// Amount related to the original transaction.
/// </summary>
public partial record OriginalTransactionAmount2
{
    #nullable enable
    
    /// <summary>
    /// Qualifies the amount of the transaction.
    /// </summary>
    public TypeOfAmount22Code? AmountQualifier { get; init; } 
    /// <summary>
    /// Actual amount of the transaction.
    /// </summary>
    public required TransactionAmount1 TransactionAmount { get; init; } 
    /// <summary>
    /// Amount to be billed to cardholder.
    /// </summary>
    public Amount15? CardholderBillingAmount { get; init; } 
    /// <summary>
    /// Amount used for reconciliation.
    /// </summary>
    public Amount15? ReconciliationAmount { get; init; } 
    
    #nullable disable
}
