//
// GENERATED CODE, DO NOT EDIT THIS FILE!
//
// Generated by ComponentGenerator for PaginationBalance2.  ISO2002 ID# _s56c4QgGEeSxsfb1OEDVsw.
//

namespace BeneficialStrategies.Iso20022.Components;

/// <summary>
/// Balance of a financial instrument for a specific statement page.
/// </summary>
public partial record PaginationBalance2
{
}
