//
// GENERATED CODE, DO NOT EDIT THIS FILE!
//
// Generated by ComponentGenerator for ResponseType6.  ISO2002 ID# _BGwWoY4YEeW6h7rGyYlyTg.
//

using BeneficialStrategies.Iso20022.Choices;
using BeneficialStrategies.Iso20022.ExternalSchema;
using BeneficialStrategies.Iso20022.UserDefined;

namespace BeneficialStrategies.Iso20022.Components;

/// <summary>
/// Response of a requested service.
/// </summary>
public partial record ResponseType6
{
    #nullable enable
    
    /// <summary>
    /// Response of the terminal manager.
    /// </summary>
    public required Response2Code Response { get; init; } 
    /// <summary>
    /// Detail of the response.
    /// </summary>
    public ResultDetail3Code? ResponseDetail { get; init; } 
    /// <summary>
    /// Additional information on the response for further examination.
    /// </summary>
    public IsoMax140Text? AdditionalResponse { get; init; } 
    
    #nullable disable
}
