//
// GENERATED CODE, DO NOT EDIT THIS FILE!
//
// Generated by ComponentGenerator for StoredValueResponse5.  ISO2002 ID# _9IcKYU4AEey_VecAUE-C9Q.
//

using BeneficialStrategies.Iso20022.Choices;

namespace BeneficialStrategies.Iso20022.Components;

/// <summary>
/// Response data to a Stored Value request.
/// </summary>
public partial record StoredValueResponse5
{
    #nullable enable
    
    /// <summary>
    /// Sale System identification of the transaction in an unambiguous way.
    /// </summary>
    public TransactionIdentifier1? SaleTransactionIdentification { get; init; } 
    /// <summary>
    /// Unique identification of a POI transaction.
    /// </summary>
    public required TransactionIdentifier1 POITransactionIdentification { get; init; } 
    /// <summary>
    /// Result of loading/reloading a stored value card.
    /// </summary>
    public StoredValueData5? Result { get; init;  } // Warning: Don't know multiplicity.
    /// <summary>
    /// Customer or Merchant payment receipt.
    /// </summary>
    public PaymentReceipt4? Receipt { get; init;  } // Warning: Don't know multiplicity.
    
    #nullable disable
}
