//
// GENERATED CODE, DO NOT EDIT THIS FILE!
//
// Generated by ComponentGenerator for TMSActionIdentification7.  ISO2002 ID# _ELZQYSi0Eeurkfo6MpvKDA.
//

namespace BeneficialStrategies.Iso20022.Components;

/// <summary>
/// Result of an individual terminal management action by the point of interaction.
/// </summary>
public partial record TMSActionIdentification7
{
}
