//
// GENERATED CODE, DO NOT EDIT THIS FILE!
//
// Generated by ComponentGenerator for UnsecuredMarketTransaction4.  ISO2002 ID# _HHn75cEREea7jLfvGi1PDw.
//

namespace BeneficialStrategies.Iso20022.Components;

/// <summary>
/// Provides the details of each individual un
/// secured market transaction.
/// </summary>
public partial record UnsecuredMarketTransaction4
{
}
