//
// GENERATED CODE, DO NOT EDIT THIS FILE!
//
// Generated by ComponentGenerator for UpdateLogSystemPartyType1.  ISO2002 ID# _5Lc0Q2jTEeiRg5NzP0jkQg.
//

namespace BeneficialStrategies.Iso20022.Components;

/// <summary>
/// Specifies the old and new values for the type of a system party.
/// </summary>
public partial record UpdateLogSystemPartyType1
{
}
