//
// GENERATED CODE, DO NOT EDIT THIS FILE!
//
// Generated by AbstractChoiceGenerator for AccountIdentification52Choice.  ISO2002 ID# _ps_Rqzi7Eeydid5dcNPKvg.
//

using System.Xml;
using System.Xml.Linq;

namespace BeneficialStrategies.Iso20022.Choices;

/// <summary>
/// Choice between all accounts (GENR - General in ISO 15022) or one or more selected accounts.
/// </summary>
[KnownType(typeof(AccountIdentification52Choice.ForAllAccounts))]
[KnownType(typeof(AccountIdentification52Choice.AccountsListAndBalanceDetails))]
public abstract partial record AccountIdentification52Choice_ : IIsoXmlSerilizable<AccountIdentification52Choice_>
{
    /// <summary>
    /// Serialize the state of this record per ISO 20022 specifications.
    /// Abstract here, overridden in each of the concrete choices.
    /// </summary>
    public abstract void Serialize(XmlWriter writer, string xmlNamespace);
    
    /// <summary>
    /// After detecting the choice being deserialized, defers the serialization of the element to the appropriate concrete choice record.
    /// </summary>
    public static AccountIdentification52Choice_ Deserialize(XElement element)
    {
        var elementWithPayload = element;
        return elementWithPayload.Name.LocalName switch
        {
             "ForAllAccts" => AccountIdentification52Choice.ForAllAccounts.Deserialize(elementWithPayload),
             "AcctsListAndBalDtls" => AccountIdentification52Choice.AccountsListAndBalanceDetails.Deserialize(elementWithPayload),
            _ => throw new InvalidOperationException($@"Xml tag '{elementWithPayload.Name.LocalName}' does not correspond to a valid AccountIdentification52Choice choice.")
        };
    }
}
