//
// GENERATED CODE, DO NOT EDIT THIS FILE!
//
// Generated by AbstractChoiceGenerator for AcknowledgedAcceptedStatus21Choice.  ISO2002 ID# _gwUucTnvEeWfSKvvZlhRKg.
//

namespace BeneficialStrategies.Iso20022.Choices;

/// <summary>
/// Specifies whether the status is provided with a reason or not.
/// </summary>
[KnownType(typeof(AcknowledgedAcceptedStatus21Choice.NoSpecifiedReason))]
[KnownType(typeof(AcknowledgedAcceptedStatus21Choice.Reason))]
[DataContract]
public abstract partial record AcknowledgedAcceptedStatus21Choice_
{
}
