//
// GENERATED CODE, DO NOT EDIT THIS FILE!
//
// Generated by AbstractChoiceGenerator for AirportName1Choice.  ISO2002 ID# _SsSlI9p-Ed-ak6NoX_4Aeg_-992731401.
//

using System.Xml;
using System.Xml.Linq;

namespace BeneficialStrategies.Iso20022.Choices;

/// <summary>
/// Identifies an airport by its code or by its name and the town where it is located.
/// </summary>
[KnownType(typeof(AirportName1Choice.AirportCode))]
[KnownType(typeof(AirportName1Choice.OtherAirportDescription))]
public abstract partial record AirportName1Choice_ : IIsoXmlSerilizable<AirportName1Choice_>
{
    /// <summary>
    /// Serialize the state of this record per ISO 20022 specifications.
    /// Abstract here, overridden in each of the concrete choices.
    /// </summary>
    public abstract void Serialize(XmlWriter writer, string xmlNamespace);
    
    /// <summary>
    /// After detecting the choice being deserialized, defers the serialization of the element to the appropriate concrete choice record.
    /// </summary>
    public static AirportName1Choice_ Deserialize(XElement element)
    {
        var elementWithPayload = element;
        return elementWithPayload.Name.LocalName switch
        {
             "AirprtCd" => AirportName1Choice.AirportCode.Deserialize(elementWithPayload),
             "OthrAirprtDesc" => AirportName1Choice.OtherAirportDescription.Deserialize(elementWithPayload),
            _ => throw new InvalidOperationException($@"Xml tag '{elementWithPayload.Name.LocalName}' does not correspond to a valid AirportName1Choice choice.")
        };
    }
}
