//
// GENERATED CODE, DO NOT EDIT THIS FILE!
//
// Generated by AbstractChoiceGenerator for AllocationSatus4Choice.  ISO2002 ID# _8QboZZNLEeWGlc8L7oPDIg.
//

using System.Xml;
using System.Xml.Linq;

namespace BeneficialStrategies.Iso20022.Choices;

/// <summary>
/// Choice of format for the allocation status reason.
/// </summary>
[KnownType(typeof(AllocationSatus4Choice.Code))]
[KnownType(typeof(AllocationSatus4Choice.Proprietary))]
public abstract partial record AllocationSatus4Choice_ : IIsoXmlSerilizable<AllocationSatus4Choice_>
{
    /// <summary>
    /// Serialize the state of this record per ISO 20022 specifications.
    /// Abstract here, overridden in each of the concrete choices.
    /// </summary>
    public abstract void Serialize(XmlWriter writer, string xmlNamespace);
    
    /// <summary>
    /// After detecting the choice being deserialized, defers the serialization of the element to the appropriate concrete choice record.
    /// </summary>
    public static AllocationSatus4Choice_ Deserialize(XElement element)
    {
        var elementWithPayload = element;
        return elementWithPayload.Name.LocalName switch
        {
             "Cd" => AllocationSatus4Choice.Code.Deserialize(elementWithPayload),
             "Prtry" => AllocationSatus4Choice.Proprietary.Deserialize(elementWithPayload),
            _ => throw new InvalidOperationException($@"Xml tag '{elementWithPayload.Name.LocalName}' does not correspond to a valid AllocationSatus4Choice choice.")
        };
    }
}
