//
// GENERATED CODE, DO NOT EDIT THIS FILE!
//
// Generated by AbstractChoiceGenerator for ChargeType8Choice.  ISO2002 ID# _qPIXQZ9BEeqxTNfi5y7ywQ.
//

using System.Xml;
using System.Xml.Linq;

namespace BeneficialStrategies.Iso20022.Choices;

/// <summary>
/// Choice of formats for a type of cost or charge.
/// </summary>
[KnownType(typeof(ChargeType8Choice.Code))]
[KnownType(typeof(ChargeType8Choice.Proprietary))]
public abstract partial record ChargeType8Choice_ : IIsoXmlSerilizable<ChargeType8Choice_>
{
    /// <summary>
    /// Serialize the state of this record per ISO 20022 specifications.
    /// Abstract here, overridden in each of the concrete choices.
    /// </summary>
    public abstract void Serialize(XmlWriter writer, string xmlNamespace);
    
    /// <summary>
    /// After detecting the choice being deserialized, defers the serialization of the element to the appropriate concrete choice record.
    /// </summary>
    public static ChargeType8Choice_ Deserialize(XElement element)
    {
        var elementWithPayload = element;
        return elementWithPayload.Name.LocalName switch
        {
             "Cd" => ChargeType8Choice.Code.Deserialize(elementWithPayload),
             "Prtry" => ChargeType8Choice.Proprietary.Deserialize(elementWithPayload),
            _ => throw new InvalidOperationException($@"Xml tag '{elementWithPayload.Name.LocalName}' does not correspond to a valid ChargeType8Choice choice.")
        };
    }
}
