//
// GENERATED CODE, DO NOT EDIT THIS FILE!
//
// Generated by AbstractChoiceGenerator for Cleared12Choice.  ISO2002 ID# _BT5_1-xYEemioJdkOVFBdw.
//

using System.Xml;
using System.Xml.Linq;

#if NET6_0_OR_GREATER // C# 10 
#else
using System.DateOnly=System.DateTime; // So data types will degrade gracefully
using System.TimeOnly=System.DateTime; // Same with this data type
#endif
namespace BeneficialStrategies.Iso20022.Choices
{
    /// <summary>
    /// Indicates whether the contract was cleared or not.
    /// </summary>
    [KnownType(typeof(Cleared12Choice.Cleared))]
    [KnownType(typeof(Cleared12Choice.IntendToClear))]
    [KnownType(typeof(Cleared12Choice.NonCleared))]
    [IsoId("_BT5_1-xYEemioJdkOVFBdw")]
    [DisplayName("Cleared 12 Choice")]
    #if DECLARE_SERIALIZABLE
    [Serializable]
    #endif
    #if DECLARE_DATACONTRACT
    [DataContract]
    #endif
    #if NET5_0_OR_GREATER // C# 9 Records, init-only setters, data annotations native
    public abstract partial record Cleared12Choice_
    #else
    public abstract partial class Cleared12Choice_
    #endif
    {
    }
}
