//
// GENERATED CODE, DO NOT EDIT THIS FILE!
//
// Generated by AbstractChoiceGenerator for CorporateActionChangeType1FormatChoice.  ISO2002 ID# _Rl9PNtp-Ed-ak6NoX_4Aeg_-146388602.
//

using System.Xml;
using System.Xml.Linq;

namespace BeneficialStrategies.Iso20022.Choices;

/// <summary>
/// Choice of formats to express the type of changes.
/// </summary>
[KnownType(typeof(CorporateActionChangeType1FormatChoice.Code))]
[KnownType(typeof(CorporateActionChangeType1FormatChoice.Proprietary))]
public abstract partial record CorporateActionChangeType1FormatChoice_ : IIsoXmlSerilizable<CorporateActionChangeType1FormatChoice_>
{
    /// <summary>
    /// Serialize the state of this record per ISO 20022 specifications.
    /// Abstract here, overridden in each of the concrete choices.
    /// </summary>
    public abstract void Serialize(XmlWriter writer, string xmlNamespace);
    
    /// <summary>
    /// After detecting the choice being deserialized, defers the serialization of the element to the appropriate concrete choice record.
    /// </summary>
    public static CorporateActionChangeType1FormatChoice_ Deserialize(XElement element)
    {
        var elementWithPayload = element;
        return elementWithPayload.Name.LocalName switch
        {
             "Cd" => CorporateActionChangeType1FormatChoice.Code.Deserialize(elementWithPayload),
             "Prtry" => CorporateActionChangeType1FormatChoice.Proprietary.Deserialize(elementWithPayload),
            _ => throw new InvalidOperationException($@"Xml tag '{elementWithPayload.Name.LocalName}' does not correspond to a valid CorporateActionChangeType1FormatChoice choice.")
        };
    }
}
