//
// GENERATED CODE, DO NOT EDIT THIS FILE!
//
// Generated by AbstractChoiceGenerator for FinancialInstrumentIdentification9Choice.  ISO2002 ID# _26V3lZ3DEeuwmdq0KtnICg.
//

using System.Xml;
using System.Xml.Linq;

namespace BeneficialStrategies.Iso20022.Choices;

/// <summary>
/// Choice between formats for the identification of the financial instruments.
/// </summary>
[KnownType(typeof(FinancialInstrumentIdentification9Choice.ISIN))]
[KnownType(typeof(FinancialInstrumentIdentification9Choice.Index))]
public abstract partial record FinancialInstrumentIdentification9Choice_ : IIsoXmlSerilizable<FinancialInstrumentIdentification9Choice_>
{
    /// <summary>
    /// Serialize the state of this record per ISO 20022 specifications.
    /// Abstract here, overridden in each of the concrete choices.
    /// </summary>
    public abstract void Serialize(XmlWriter writer, string xmlNamespace);
    
    /// <summary>
    /// After detecting the choice being deserialized, defers the serialization of the element to the appropriate concrete choice record.
    /// </summary>
    public static FinancialInstrumentIdentification9Choice_ Deserialize(XElement element)
    {
        var elementWithPayload = element;
        return elementWithPayload.Name.LocalName switch
        {
             "ISIN" => FinancialInstrumentIdentification9Choice.ISIN.Deserialize(elementWithPayload),
             "Indx" => FinancialInstrumentIdentification9Choice.Index.Deserialize(elementWithPayload),
            _ => throw new InvalidOperationException($@"Xml tag '{elementWithPayload.Name.LocalName}' does not correspond to a valid FinancialInstrumentIdentification9Choice choice.")
        };
    }
}
