//
// GENERATED CODE, DO NOT EDIT THIS FILE!
//
// Generated by AbstractChoiceGenerator for AcknowledgedAcceptedStatus24Choice.  ISO2002 ID# _OcXnITq5EeWyoP0PbocV1Q.
//

namespace BeneficialStrategies.Iso20022.Choices;

/// <summary>
/// Specifies whether the status is provided with a reason or not.
/// </summary>
public partial interface IAcknowledgedAcceptedStatus24Choice
{
}
