//
// GENERATED CODE, DO NOT EDIT THIS FILE!
//
// Generated by AbstractChoiceGenerator for CancellationReason28Choice.  ISO2002 ID# _6QFgqZNLEeWGlc8L7oPDIg.
//

namespace BeneficialStrategies.Iso20022.Choices;

/// <summary>
/// Choice of format for the cancellation reason.
/// </summary>
public partial interface ICancellationReason28Choice
{
}
