//
// GENERATED CODE, DO NOT EDIT THIS FILE!
//
// Generated by AbstractChoiceGenerator for DateOrDateTimePeriod3Choice.  ISO2002 ID# _Fk5tk_1bEeiAfJEqh4xF_Q.
//

namespace BeneficialStrategies.Iso20022.Choices;

/// <summary>
/// Choice between a date or a date and time format for a period.
/// </summary>
public partial interface IDateOrDateTimePeriod3Choice
{
}
