//
// GENERATED CODE, DO NOT EDIT THIS FILE!
//
// Generated by AbstractChoiceGenerator for LimitStructure1Choice.  ISO2002 ID# _72iECKMgEeCJ6YNENx4h-w_-879339844.
//

namespace BeneficialStrategies.Iso20022.Choices;

/// <summary>
/// Limit details of one or more limits set by the member and managed by the transaction administrator.
/// </summary>
public partial interface ILimitStructure1Choice
{
}
