//
// GENERATED CODE, DO NOT EDIT THIS FILE!
//
// Generated by AbstractChoiceGenerator for ModificationReason2Choice.  ISO2002 ID# _0jrN8glIEeGATtfOBToyew_727548806.
//

namespace BeneficialStrategies.Iso20022.Choices;

/// <summary>
/// Choice of format for the Modification reason.
/// </summary>
public partial interface IModificationReason2Choice
{
}
