//
// GENERATED CODE, DO NOT EDIT THIS FILE!
//
// Generated by AbstractChoiceGenerator for PartyIdentification1Choice.  ISO2002 ID# _QQR1v9p-Ed-ak6NoX_4Aeg_-1748201287.
//

namespace BeneficialStrategies.Iso20022.Choices;

/// <summary>
/// Identification of a party.
/// </summary>
public partial interface IPartyIdentification1Choice
{
}
