//
// GENERATED CODE, DO NOT EDIT THIS FILE!
//
// Generated by AbstractChoiceGenerator for RateType23Choice.  ISO2002 ID# _3LapmRLnEeKJ5uSjVyVvug.
//

namespace BeneficialStrategies.Iso20022.Choices;

/// <summary>
/// Choice between a standard code or proprietary code to specify a rate type.
/// </summary>
public partial interface IRateType23Choice
{
}
