//
// GENERATED CODE, DO NOT EDIT THIS FILE!
//
// Generated by AbstractChoiceGenerator for References34Choice.  ISO2002 ID# _jvDnxu5NEeCisYr99QEiWA_1809359150.
//

namespace BeneficialStrategies.Iso20022.Choices;

/// <summary>
/// Choice of references.
/// </summary>
public partial interface IReferences34Choice
{
}
