//
// GENERATED CODE, DO NOT EDIT THIS FILE!
//
// Generated by AbstractChoiceGenerator for LegalFramework3Choice.  ISO2002 ID# _-5gGQTqkEeWyoP0PbocV1Q.
//

namespace BeneficialStrategies.Iso20022.Choices;

/// <summary>
/// Choice of format for the legal framework.
/// </summary>
[KnownType(typeof(LegalFramework3Choice.Code))]
[KnownType(typeof(LegalFramework3Choice.Proprietary))]
public abstract partial record LegalFramework3Choice_
{
}
