//
// GENERATED CODE, DO NOT EDIT THIS FILE!
//
// Generated by AbstractChoiceGenerator for MarginTerms1Choice.  ISO2002 ID# _QmogMtp-Ed-ak6NoX_4Aeg_86732419.
//

using System.Xml;
using System.Xml.Linq;

namespace BeneficialStrategies.Iso20022.Choices;

/// <summary>
/// Provides the margin terms for the variation margin and the segregated independent amount, or the segregated independent amount only.
/// </summary>
[KnownType(typeof(MarginTerms1Choice.MarginDetails))]
[KnownType(typeof(MarginTerms1Choice.SegregatedIndependentAmountMargin))]
public abstract partial record MarginTerms1Choice_ : IIsoXmlSerilizable<MarginTerms1Choice_>
{
    /// <summary>
    /// Serialize the state of this record per ISO 20022 specifications.
    /// Abstract here, overridden in each of the concrete choices.
    /// </summary>
    public abstract void Serialize(XmlWriter writer, string xmlNamespace);
    
    /// <summary>
    /// After detecting the choice being deserialized, defers the serialization of the element to the appropriate concrete choice record.
    /// </summary>
    public static MarginTerms1Choice_ Deserialize(XElement element)
    {
        var elementWithPayload = element;
        return elementWithPayload.Name.LocalName switch
        {
             "MrgnDtls" => MarginTerms1Choice.MarginDetails.Deserialize(elementWithPayload),
             "SgrtdIndpdntAmtMrgn" => MarginTerms1Choice.SegregatedIndependentAmountMargin.Deserialize(elementWithPayload),
            _ => throw new InvalidOperationException($@"Xml tag '{elementWithPayload.Name.LocalName}' does not correspond to a valid MarginTerms1Choice choice.")
        };
    }
}
