//
// GENERATED CODE, DO NOT EDIT THIS FILE!
//
// Generated by AbstractChoiceGenerator for PartyOrOperationalError3Choice.  ISO2002 ID# _7VYvRVhLEeih3fUfzR38Ig.
//

using System.Xml;
using System.Xml.Linq;

namespace BeneficialStrategies.Iso20022.Choices;

/// <summary>
/// Report between the party reference data or an operational error.
/// </summary>
[KnownType(typeof(PartyOrOperationalError3Choice.PartyReport))]
[KnownType(typeof(PartyOrOperationalError3Choice.OperationalError))]
public abstract partial record PartyOrOperationalError3Choice_ : IIsoXmlSerilizable<PartyOrOperationalError3Choice_>
{
    /// <summary>
    /// Serialize the state of this record per ISO 20022 specifications.
    /// Abstract here, overridden in each of the concrete choices.
    /// </summary>
    public abstract void Serialize(XmlWriter writer, string xmlNamespace);
    
    /// <summary>
    /// After detecting the choice being deserialized, defers the serialization of the element to the appropriate concrete choice record.
    /// </summary>
    public static PartyOrOperationalError3Choice_ Deserialize(XElement element)
    {
        var elementWithPayload = element;
        return elementWithPayload.Name.LocalName switch
        {
             "PtyRpt" => PartyOrOperationalError3Choice.PartyReport.Deserialize(elementWithPayload),
             "OprlErr" => PartyOrOperationalError3Choice.OperationalError.Deserialize(elementWithPayload),
            _ => throw new InvalidOperationException($@"Xml tag '{elementWithPayload.Name.LocalName}' does not correspond to a valid PartyOrOperationalError3Choice choice.")
        };
    }
}
