//
// GENERATED CODE, DO NOT EDIT THIS FILE!
//
// Generated by AbstractChoiceGenerator for Proxy3Choice.  ISO2002 ID# _j7B_sa09EemDtrWpq90Ckg.
//

namespace BeneficialStrategies.Iso20022.Choices;

/// <summary>
/// Choice of proxy allowance.
/// </summary>
[KnownType(typeof(Proxy3Choice.Proxy))]
[KnownType(typeof(Proxy3Choice.ProxyNotAllowed))]
[DataContract]
public abstract partial record Proxy3Choice_
{
}
