//
// GENERATED CODE, DO NOT EDIT THIS FILE!
//
// Generated by AbstractChoiceGenerator for RejectedReason23Choice.  ISO2002 ID# _kov6b5wsEeazcsnODTksnQ.
//

namespace BeneficialStrategies.Iso20022.Choices;

/// <summary>
/// Choice between a standard code or proprietary code to specify the reason why the instruction or cancellation request has a rejected status.
/// </summary>
[KnownType(typeof(RejectedReason23Choice.Code))]
[KnownType(typeof(RejectedReason23Choice.Proprietary))]
[DataContract]
public abstract partial record RejectedReason23Choice_
{
}
