//
// GENERATED CODE, DO NOT EDIT THIS FILE!
//
// Generated by AbstractChoiceGenerator for TaxCapacityParty3Choice.  ISO2002 ID# _AZHgFNokEeC60axPepSq7g_1368960852.
//

using System.Xml;
using System.Xml.Linq;

namespace BeneficialStrategies.Iso20022.Choices;

/// <summary>
/// Choice of format for the tax capacity information.
/// </summary>
[KnownType(typeof(TaxCapacityParty3Choice.Code))]
[KnownType(typeof(TaxCapacityParty3Choice.Proprietary))]
public abstract partial record TaxCapacityParty3Choice_ : IIsoXmlSerilizable<TaxCapacityParty3Choice_>
{
    /// <summary>
    /// Serialize the state of this record per ISO 20022 specifications.
    /// Abstract here, overridden in each of the concrete choices.
    /// </summary>
    public abstract void Serialize(XmlWriter writer, string xmlNamespace);
    
    /// <summary>
    /// After detecting the choice being deserialized, defers the serialization of the element to the appropriate concrete choice record.
    /// </summary>
    public static TaxCapacityParty3Choice_ Deserialize(XElement element)
    {
        var elementWithPayload = element;
        return elementWithPayload.Name.LocalName switch
        {
             "Cd" => TaxCapacityParty3Choice.Code.Deserialize(elementWithPayload),
             "Prtry" => TaxCapacityParty3Choice.Proprietary.Deserialize(elementWithPayload),
            _ => throw new InvalidOperationException($@"Xml tag '{elementWithPayload.Name.LocalName}' does not correspond to a valid TaxCapacityParty3Choice choice.")
        };
    }
}
