//
// GENERATED CODE, DO NOT EDIT THIS FILE!
//
// Generated by AbstractChoiceGenerator for UnderlyingContract2Choice.  ISO2002 ID# _JXX9CW49EeiU9cctagi5ow.
//

namespace BeneficialStrategies.Iso20022.Choices;

/// <summary>
/// Choice of the type of underlying contract.
/// </summary>
[KnownType(typeof(UnderlyingContract2Choice.Loan))]
[KnownType(typeof(UnderlyingContract2Choice.Trade))]
public abstract partial record UnderlyingContract2Choice_
{
}
