//
// GENERATED CODE, DO NOT EDIT THIS FILE!
//
// Generated by AbstractChoiceGenerator for UpdateType29Choice.  ISO2002 ID# _ubeXIcvGEeihG9bKfarOOA.
//

using System.Xml;
using System.Xml.Linq;

namespace BeneficialStrategies.Iso20022.Choices;

/// <summary>
/// Specifies the type of update requested. That is addition, deletion or modification.
/// </summary>
[KnownType(typeof(UpdateType29Choice.Addition))]
[KnownType(typeof(UpdateType29Choice.Deletion))]
[KnownType(typeof(UpdateType29Choice.Modification))]
public abstract partial record UpdateType29Choice_ : IIsoXmlSerilizable<UpdateType29Choice_>
{
    /// <summary>
    /// Serialize the state of this record per ISO 20022 specifications.
    /// Abstract here, overridden in each of the concrete choices.
    /// </summary>
    public abstract void Serialize(XmlWriter writer, string xmlNamespace);
    
    /// <summary>
    /// After detecting the choice being deserialized, defers the serialization of the element to the appropriate concrete choice record.
    /// </summary>
    public static UpdateType29Choice_ Deserialize(XElement element)
    {
        var elementWithPayload = element;
        return elementWithPayload.Name.LocalName switch
        {
             "Addtn" => UpdateType29Choice.Addition.Deserialize(elementWithPayload),
             "Deltn" => UpdateType29Choice.Deletion.Deserialize(elementWithPayload),
             "Mod" => UpdateType29Choice.Modification.Deserialize(elementWithPayload),
            _ => throw new InvalidOperationException($@"Xml tag '{elementWithPayload.Name.LocalName}' does not correspond to a valid UpdateType29Choice choice.")
        };
    }
}
