//
// GENERATED CODE, DO NOT EDIT THIS FILE!
//
// Generated by AbstractChoiceGenerator for UpdateType33Choice.  ISO2002 ID# _lg1sUQleEeuQ1MenzX1l-g.
//

namespace BeneficialStrategies.Iso20022.Choices;

/// <summary>
/// Specifies the type of update requested. That is addition, deletion or modification.
/// </summary>
[KnownType(typeof(UpdateType33Choice.Addition))]
[KnownType(typeof(UpdateType33Choice.Deletion))]
[KnownType(typeof(UpdateType33Choice.Modification))]
public abstract partial record UpdateType33Choice_
{
}
