//
// GENERATED CODE, DO NOT EDIT THIS FILE!
//
// Generated by ConcreteChoiceGenerator for NominalValue.  ISO2002 ID# _AqItcYIiEeW_KPkCyw2GUA.
//

namespace BeneficialStrategies.Iso20022.Choices.FinancialInstrumentQuantity25Choice;

/// <summary>
/// TBC.
/// </summary>
public partial record NominalValue : IFinancialInstrumentQuantity25Choice
{
    // Members coming soon...
}
