//
// GENERATED CODE, DO NOT EDIT THIS FILE!
//
// Generated by ConcreteChoiceGenerator for Code.  ISO2002 ID# _aM8ewTqkEeWyoP0PbocV1Q.
//

using BeneficialStrategies.Iso20022.Components;
using BeneficialStrategies.Iso20022.ExternalSchema;

namespace BeneficialStrategies.Iso20022.Choices.DateCode18Choice;

/// <summary>
/// Date expressed as an ISO 20022 code.
/// </summary>
public partial record Code : DateCode18Choice_
{
    public required DateType5Code Value { get; init; }
}
