//
// GENERATED CODE, DO NOT EDIT THIS FILE!
//
// Generated by ConcreteChoiceGenerator for RejectionReason.  ISO2002 ID# _gAQ5kzi8Eeydid5dcNPKvg.
//

namespace BeneficialStrategies.Iso20022.Choices.Reason20Choice;

/// <summary>
/// Specifies the reason why the instruction/request has a rejected status.
/// </summary>
public partial record RejectionReason : IReason20Choice
{
    // Members coming soon...
}
