//
// GENERATED CODE, DO NOT EDIT THIS FILE!
//
// Generated by ConcreteChoiceGenerator for Return.  ISO2002 ID# _6gAQYyqREeyR9JrVGfaMKw.
//

namespace BeneficialStrategies.Iso20022.Choices.CollateralMovement6Choice;

/// <summary>
/// Provides the collateral movement direction that is a return only.
/// </summary>
public partial record Return : ICollateralMovement6Choice
{
    // Members coming soon...
}
