//
// GENERATED CODE, DO NOT EDIT THIS FILE!
//
// Generated by ConcreteChoiceGenerator for FinancialInstrumentIdentification.  ISO2002 ID# __ioAQRIoEeyZaPkaPAzTvQ.
//

using BeneficialStrategies.Iso20022.Components;
using BeneficialStrategies.Iso20022.ExternalSchema;
using System.Xml;
using System.Xml.Linq;

namespace BeneficialStrategies.Iso20022.Choices.RemovalProcessing2Choice;

/// <summary>
/// Financial instrument representing a sum of rights of the investor vis-a-vis the issuer.
/// </summary>
public partial record FinancialInstrumentIdentification : RemovalProcessing2Choice_
     , IIsoXmlSerilizable<FinancialInstrumentIdentification>
{
    #nullable enable
    
    /// <summary>
    /// International Securities Identification Number (ISIN). A numbering system designed by the United Nation's International Organisation for Standardisation (ISO). The ISIN is composed of a 2-character prefix representing the country of issue, followed by the national security number (if one exists), and a check digit. Each country has a national numbering agency that assigns ISIN numbers for securities in that country.
    /// </summary>
    public IsoISINOct2015Identifier? ISIN { get; init; } 
    /// <summary>
    /// Identification of a security by proprietary or domestic identification scheme.
    /// </summary>
    public OtherIdentification1? OtherIdentification { get; init; } 
    /// <summary>
    /// Textual description of a security instrument.
    /// </summary>
    public IsoMax140Text? Description { get; init; } 
    
    #nullable disable
    
    
    /// <summary>
    /// Used to format the various primative types during serialization.
    /// </summary>
    public static SerializationFormatter SerializationFormatter { get; set; } = SerializationFormatter.GlobalInstance;
    
    /// <summary>
    /// Serializes the state of this record according to Iso20022 specifications.
    /// </summary>
    public override void Serialize(XmlWriter writer, string xmlNamespace)
    {
        if (ISIN is IsoISINOct2015Identifier ISINValue)
        {
            writer.WriteStartElement(null, "ISIN", xmlNamespace );
            writer.WriteValue(SerializationFormatter.IsoISINOct2015Identifier(ISINValue)); // data type ISINOct2015Identifier System.String
            writer.WriteEndElement();
        }
        if (OtherIdentification is OtherIdentification1 OtherIdentificationValue)
        {
            writer.WriteStartElement(null, "OthrId", xmlNamespace );
            OtherIdentificationValue.Serialize(writer, xmlNamespace);
            writer.WriteEndElement();
        }
        if (Description is IsoMax140Text DescriptionValue)
        {
            writer.WriteStartElement(null, "Desc", xmlNamespace );
            writer.WriteValue(SerializationFormatter.IsoMax140Text(DescriptionValue)); // data type Max140Text System.String
            writer.WriteEndElement();
        }
    }
    public static new FinancialInstrumentIdentification Deserialize(XElement element)
    {
        throw new NotImplementedException();
    }
}
