//
// GENERATED CODE, DO NOT EDIT THIS FILE!
//
// Generated by ConcreteChoiceGenerator for LEI.  ISO2002 ID# _unMS4EW8EeWaZZ6gWK8UVw.
//

namespace BeneficialStrategies.Iso20022.Choices.DerivativePartyIdentification1Choice;

/// <summary>
/// Identification of the reference party through Legal entity identifier.
/// </summary>
public partial record LEI : IDerivativePartyIdentification1Choice
{
    // Members coming soon...
}
