//
// GENERATED CODE, DO NOT EDIT THIS FILE!
//
// Generated by CodesetEnumGenerator for AcknowledgementReasonCode.  ISO2002 ID# _bpZDBtp-Ed-ak6NoX_4Aeg_423330067.
//

using System.Reflection;
using System.Runtime.Serialization;

namespace BeneficialStrategies.Iso20222.Common;

/// <summary>
/// Specifies additional information about the processed instruction.
/// </summary>
[DataContract]
[Serializable]
[IsoId("_bpZDBtp-Ed-ak6NoX_4Aeg_423330067")]
[Description(@"Specifies additional information about the processed instruction.")]
public enum AcknowledgementReasonCode
{
    /// <summary>
    /// Received after the account servicer's deadline. Processed on best effort basis.
    /// </summary>
    [EnumMember(Value = "ADEA")]
    [IsoId("_bpZDB9p-Ed-ak6NoX_4Aeg_309491001")]
    [Description(@"Received after the account servicer's deadline. Processed on best effort basis.")]
    ADEA,
    
    /// <summary>
    /// Instruction is accepted but does not comply with the market practice rule published for the concerned market or process.
    /// </summary>
    [EnumMember(Value = "SMPG")]
    [IsoId("_bpZDCNp-Ed-ak6NoX_4Aeg_-865700024")]
    [Description(@"Instruction is accepted but does not comply with the market practice rule published for the concerned market or process.")]
    SMPG,
    
    /// <summary>
    /// Instruction was received after market deadline.
    /// </summary>
    [EnumMember(Value = "LATE")]
    [IsoId("_bpi0ANp-Ed-ak6NoX_4Aeg_-1570814639")]
    [Description(@"Instruction was received after market deadline.")]
    LATE,
    
    /// <summary>
    /// Instruction was not straight through processing and had to be processed manually.
    /// </summary>
    [EnumMember(Value = "NSTP")]
    [IsoId("_bpi0Adp-Ed-ak6NoX_4Aeg_74452796")]
    [Description(@"Instruction was not straight through processing and had to be processed manually.")]
    NSTP,
    
    /// <summary>
    /// Instruction registration is accepted but the registration is not in full, that is, not with voting rights.
    /// </summary>
    [EnumMember(Value = "RQWV")]
    [IsoId("_bpi0Atp-Ed-ak6NoX_4Aeg_1613241238")]
    [Description(@"Instruction registration is accepted but the registration is not in full, that is, not with voting rights.")]
    RQWV,
    
    /// <summary>
    /// Other. See Narrative.
    /// </summary>
    [EnumMember(Value = "OTHR")]
    [IsoId("_bpi0A9p-Ed-ak6NoX_4Aeg_-39849136")]
    [Description(@"Other. See Narrative.")]
    OTHR,
    
    /// <summary>
    /// Execution is conditional to the execution of a process linked to the currency of the transaction.
    /// </summary>
    [EnumMember(Value = "CDCY")]
    [IsoId("_bpi0BNp-Ed-ak6NoX_4Aeg_277271")]
    [Description(@"Execution is conditional to the execution of a process linked to the currency of the transaction.")]
    CDCY,
    
    /// <summary>
    /// Execution is conditional to the execution of a process at the registrar.
    /// </summary>
    [EnumMember(Value = "CDRG")]
    [IsoId("_bpi0Bdp-Ed-ak6NoX_4Aeg_-732594298")]
    [Description(@"Execution is conditional to the execution of a process at the registrar.")]
    CDRG,
    
    /// <summary>
    /// Execution is conditional to the execution of a process of realignment at the issuer CSD.
    /// </summary>
    [EnumMember(Value = "CDRE")]
    [IsoId("_bpi0Btp-Ed-ak6NoX_4Aeg_1822773303")]
    [Description(@"Execution is conditional to the execution of a process of realignment at the issuer CSD.")]
    CDRE,
    
    /// <summary>
    /// See narrative field for reason.
    /// </summary>
    [EnumMember(Value = "NARR")]
    [IsoId("_-23l4Cz1EeOsiuMH68so7Q")]
    [Description(@"See narrative field for reason.")]
    NARR,
    
}


/// <summary>
/// Provides access to the metadata associated with a specific enum.
/// </summary>
public static class AcknowledgementReasonCodeMetadataExtensions
{
    private static readonly AcknowledgementReasonCodeDropdownSource _dropdownSource = new AcknowledgementReasonCodeDropdownSource();

    /// <summary>
    /// Returns the metadata associated with this enum value.
    /// </summary>
    public static IAcknowledgementReasonCodeDropdownRow GetMetadata(this AcknowledgementReasonCode code)
    {
        return _dropdownSource.Lookup(code) ;
    }
}


