//
// GENERATED CODE, DO NOT EDIT THIS FILE!
//
// Generated by CodesetEnumGenerator for ConditionallyAcceptedStatusReason1Code.  ISO2002 ID# _Vjk7Vtp-Ed-ak6NoX_4Aeg_-149220072.
//

using System.Reflection;
using System.Runtime.Serialization;

namespace BeneficialStrategies.Iso20222.Common;

/// <summary>
/// Specifies the reason for a conditionally accepted status.
/// </summary>
[DataContract]
[Serializable]
[IsoId("_Vjk7Vtp-Ed-ak6NoX_4Aeg_-149220072")]
[Description(@"Specifies the reason for a conditionally accepted status.")]
[DerivedFrom(typeof(ConditionallyAcceptedStatusReasonCode))]
public enum ConditionallyAcceptedStatusReason1Code
{
    /// <summary>
    /// ??
    /// Encoded/decoded by serializers as "AwaitingMoney".
    /// </summary>
    [EnumMember(Value = "")]
    [IsoId("_Vjk7V9p-Ed-ak6NoX_4Aeg_-123362029")]
    [Description(@"??")]
    AwaitingMoney,
    
    /// <summary>
    /// ??
    /// Encoded/decoded by serializers as "AwaitingFunds".
    /// </summary>
    [EnumMember(Value = "")]
    [IsoId("_Vjk7WNp-Ed-ak6NoX_4Aeg_351329874")]
    [Description(@"??")]
    AwaitingFunds,
    
    /// <summary>
    /// ??
    /// Encoded/decoded by serializers as "AwaitingDocuments".
    /// </summary>
    [EnumMember(Value = "")]
    [IsoId("_VjusUNp-Ed-ak6NoX_4Aeg_411359154")]
    [Description(@"??")]
    AwaitingDocuments,
    
    /// <summary>
    /// ??
    /// Encoded/decoded by serializers as "Other".
    /// </summary>
    [EnumMember(Value = "")]
    [IsoId("_VjusUdp-Ed-ak6NoX_4Aeg_-187465798")]
    [Description(@"??")]
    Other,
    
}


/// <summary>
/// Provides access to the metadata associated with a specific enum.
/// </summary>
public static class ConditionallyAcceptedStatusReason1CodeMetadataExtensions
{
    private static readonly ConditionallyAcceptedStatusReason1CodeDropdownSource _dropdownSource = new ConditionallyAcceptedStatusReason1CodeDropdownSource();

    /// <summary>
    /// Returns the metadata associated with this enum value.
    /// </summary>
    public static IConditionallyAcceptedStatusReason1CodeDropdownRow GetMetadata(this ConditionallyAcceptedStatusReason1Code code)
    {
        return _dropdownSource.Lookup(code) ;
    }
}


