//
// GENERATED CODE, DO NOT EDIT THIS FILE!
//
// Generated by CodesetEnumGenerator for GeneralInvestmentAccountType1Code.  ISO2002 ID# _bk_q4F2dEeiFXdiLi_Nf4A.
//

using System.Reflection;
using System.Runtime.Serialization;

namespace BeneficialStrategies.Iso20222.Common;

/// <summary>
/// Specifies a type of investment account.
/// </summary>
[DataContract]
[Serializable]
[IsoId("_bk_q4F2dEeiFXdiLi_Nf4A")]
[Description(@"Specifies a type of investment account.")]
[DerivedFrom(typeof(GeneralInvestmentAccountTypeCode))]
public enum GeneralInvestmentAccountType1Code
{
    /// <summary>
    /// General shares or equity savings account.
    /// Encoded/decoded by serializers as "EQUI".
    /// </summary>
    [EnumMember(Value = "EQUI")]
    [IsoId("_dqv2cV2dEeiFXdiLi_Nf4A")]
    [Description(@"General shares or equity savings account.")]
    ShareSavingsAccount = GeneralInvestmentAccountTypeCode.ShareSavingsAccount, // same ordinal as derivation source for type conversions
    
}


/// <summary>
/// Provides access to the metadata associated with a specific enum.
/// </summary>
public static class GeneralInvestmentAccountType1CodeMetadataExtensions
{
    private static readonly GeneralInvestmentAccountType1CodeDropdownSource _dropdownSource = new GeneralInvestmentAccountType1CodeDropdownSource();
    
    /// <summary>
    /// Returns the metadata associated with this enum value.
    /// </summary>
    public static IGeneralInvestmentAccountType1CodeDropdownRow GetMetadata(this GeneralInvestmentAccountType1Code code)
    {
        return _dropdownSource.Lookup(code) ;
    }
}


