//
// GENERATED CODE, DO NOT EDIT THIS FILE!
//
// Generated by CodesetEnumGenerator for ModelType1Code.  ISO2002 ID# _mRl-ILC2EeaSl6vJk5Bd8w.
//

using System.Reflection;
using System.Runtime.Serialization;

namespace BeneficialStrategies.Iso20222.Common;

/// <summary>
/// Categorisation of margin models used by central counterparties.
/// </summary>
[DataContract]
[Serializable]
[IsoId("_mRl-ILC2EeaSl6vJk5Bd8w")]
[Description(@"Categorisation of margin models used by central counterparties.")]
[DerivedFrom(typeof(ModelTypeCode))]
public enum ModelType1Code
{
    /// <summary>
    /// ??
    /// Encoded/decoded by serializers as "ExpectedShortfall".
    /// </summary>
    [EnumMember(Value = "")]
    [IsoId("_oGOkgbC2EeaSl6vJk5Bd8w")]
    [Description(@"??")]
    ExpectedShortfall,
    
    /// <summary>
    /// ??
    /// Encoded/decoded by serializers as "Other".
    /// </summary>
    [EnumMember(Value = "")]
    [IsoId("_oM7CYbC2EeaSl6vJk5Bd8w")]
    [Description(@"??")]
    Other,
    
    /// <summary>
    /// ??
    /// Encoded/decoded by serializers as "OtherRiskAggregation".
    /// </summary>
    [EnumMember(Value = "")]
    [IsoId("_oSISgbC2EeaSl6vJk5Bd8w")]
    [Description(@"??")]
    OtherRiskAggregation,
    
    /// <summary>
    /// ??
    /// Encoded/decoded by serializers as "Span".
    /// </summary>
    [EnumMember(Value = "")]
    [IsoId("_okRycbC2EeaSl6vJk5Bd8w")]
    [Description(@"??")]
    Span,
    
    /// <summary>
    /// ??
    /// Encoded/decoded by serializers as "ValueAtRisk".
    /// </summary>
    [EnumMember(Value = "")]
    [IsoId("_oqYacbC2EeaSl6vJk5Bd8w")]
    [Description(@"??")]
    ValueAtRisk,
    
    /// <summary>
    /// ??
    /// Encoded/decoded by serializers as "ScenarioAnalysisModel".
    /// </summary>
    [EnumMember(Value = "")]
    [IsoId("_g2MMUTW1EemdWfjs3tykFQ")]
    [Description(@"??")]
    ScenarioAnalysisModel,
    
}


/// <summary>
/// Provides access to the metadata associated with a specific enum.
/// </summary>
public static class ModelType1CodeMetadataExtensions
{
    private static readonly ModelType1CodeDropdownSource _dropdownSource = new ModelType1CodeDropdownSource();

    /// <summary>
    /// Returns the metadata associated with this enum value.
    /// </summary>
    public static IModelType1CodeDropdownRow GetMetadata(this ModelType1Code code)
    {
        return _dropdownSource.Lookup(code) ;
    }
}


