//
// GENERATED CODE, DO NOT EDIT THIS FILE!
//
// Generated by CodesetEnumGenerator for RepurchaseType2Code.  ISO2002 ID# _ZTe7ltp-Ed-ak6NoX_4Aeg_212758394.
//

using System.Reflection;
using System.Runtime.Serialization;

namespace BeneficialStrategies.Iso20222.Common;

/// <summary>
/// Specifies the type of repurchase transaction.
/// </summary>
[DataContract]
[Serializable]
[IsoId("_ZTe7ltp-Ed-ak6NoX_4Aeg_212758394")]
[Description(@"Specifies the type of repurchase transaction.")]
[DerivedFrom(typeof(RepurchaseTypeCode))]
public enum RepurchaseType2Code
{
    /// <summary>
    /// ??
    /// Encoded/decoded by serializers as "Swap".
    /// </summary>
    [EnumMember(Value = "")]
    [IsoId("_ZTe7l9p-Ed-ak6NoX_4Aeg_473191454")]
    [Description(@"??")]
    Swap,
    
    /// <summary>
    /// ??
    /// Encoded/decoded by serializers as "RepurchaseCall".
    /// </summary>
    [EnumMember(Value = "")]
    [IsoId("_ZTe7mNp-Ed-ak6NoX_4Aeg_489815295")]
    [Description(@"??")]
    RepurchaseCall,
    
    /// <summary>
    /// ??
    /// Encoded/decoded by serializers as "Pairoff".
    /// </summary>
    [EnumMember(Value = "")]
    [IsoId("_ZToskNp-Ed-ak6NoX_4Aeg_501821642")]
    [Description(@"??")]
    Pairoff,
    
    /// <summary>
    /// ??
    /// Encoded/decoded by serializers as "RepoRate".
    /// </summary>
    [EnumMember(Value = "")]
    [IsoId("_ZToskdp-Ed-ak6NoX_4Aeg_529525655")]
    [Description(@"??")]
    RepoRate,
    
    /// <summary>
    /// ??
    /// Encoded/decoded by serializers as "Rollover".
    /// </summary>
    [EnumMember(Value = "")]
    [IsoId("_ZTosktp-Ed-ak6NoX_4Aeg_560001854")]
    [Description(@"??")]
    Rollover,
    
    /// <summary>
    /// ??
    /// Encoded/decoded by serializers as "TopUp".
    /// </summary>
    [EnumMember(Value = "")]
    [IsoId("_ZTosk9p-Ed-ak6NoX_4Aeg_572932121")]
    [Description(@"??")]
    TopUp,
    
    /// <summary>
    /// ??
    /// Encoded/decoded by serializers as "Withdrawal".
    /// </summary>
    [EnumMember(Value = "")]
    [IsoId("_ZToslNp-Ed-ak6NoX_4Aeg_573855643")]
    [Description(@"??")]
    Withdrawal,
    
}


/// <summary>
/// Provides access to the metadata associated with a specific enum.
/// </summary>
public static class RepurchaseType2CodeMetadataExtensions
{
    private static readonly RepurchaseType2CodeDropdownSource _dropdownSource = new RepurchaseType2CodeDropdownSource();

    /// <summary>
    /// Returns the metadata associated with this enum value.
    /// </summary>
    public static IRepurchaseType2CodeDropdownRow GetMetadata(this RepurchaseType2Code code)
    {
        return _dropdownSource.Lookup(code) ;
    }
}


