//
// GENERATED CODE, DO NOT EDIT THIS FILE!
//
// Generated by CodesetEnumGenerator for RegistrationProcessingStatus1Code.  ISO2002 ID# _ZbFYYNp-Ed-ak6NoX_4Aeg_-586829209.
// Copyright 2024 Jeff Ward, Beneficial Strategies. Usage subject to license of enclosing library.
//

using System.Reflection;
using System.Runtime.Serialization;
using System.Text.Json.Serialization;

namespace BeneficialStrategies.Iso20022.Codesets;

/// <summary>
/// Specifies the status of the registration processing.
/// </summary>
[DataContract]
[Serializable]
[IsoId("_ZbFYYNp-Ed-ak6NoX_4Aeg_-586829209")]
[Description(@"Specifies the status of the registration processing.")]
[DerivedFrom(typeof(RegistrationProcessingStatusCode))]
#if NET8_0_OR_GREATER // C# 12 Global type alias
[JsonConverter(typeof(JsonStringEnumConverter<RegistrationProcessingStatus1Code>))]
#endif
public enum RegistrationProcessingStatus1Code
{
    /// <summary>
    /// Registration has been acknowledged/accepted by the issuer/registrar.
    /// Encoded/decoded by serializers as &quot;PACK&quot;.
    /// </summary>
    [EnumMember(Value = "PACK")]
    [IsoId("_ZbFYYdp-Ed-ak6NoX_4Aeg_-586829178")]
    [Description(@"Registration has been acknowledged/accepted by the issuer/registrar.")]
    AcknowledgedAccepted = RegistrationProcessingStatusCode.AcknowledgedAccepted, // same ordinal as derivation source for type conversions
    
    /// <summary>
    /// Registration has been rejected by the issuer/registrar.
    /// Encoded/decoded by serializers as &quot;REJT&quot;.
    /// </summary>
    [EnumMember(Value = "REJT")]
    [IsoId("_ZbFYYtp-Ed-ak6NoX_4Aeg_-586829177")]
    [Description(@"Registration has been rejected by the issuer/registrar.")]
    Rejected = RegistrationProcessingStatusCode.Rejected, // same ordinal as derivation source for type conversions
    
}
