//
// GENERATED CODE, DO NOT EDIT THIS FILE!
//
// Generated by ConcreteChoiceGenerator for FromDateToDate.  ISO2002 ID# _XEtQOa3NEeey8N0JWnVPUw.
//

using BeneficialStrategies.Iso20022.Components;
using BeneficialStrategies.Iso20022.ExternalSchema;

namespace BeneficialStrategies.Iso20022.Choices.Period5Choice;

/// <summary>
/// Time span defined by a start date and time, and an end date and time.
/// </summary>
public partial record FromDateToDate : IPeriod5Choice
{
    #nullable enable
    /// <summary>
    /// Date and time at which the range starts.
    /// </summary>
    public required IsoISODate FromDate { get; init; } 
    /// <summary>
    /// Date and time at which the range ends.
    /// </summary>
    public required IsoISODate ToDate { get; init; } 
    #nullable disable
}
