//
// GENERATED CODE, DO NOT EDIT THIS FILE!
//
// Generated by ConcreteChoiceGenerator for ItalianDomesticIdentificationCode.  ISO2002 ID# _VwSCc7NIEeejueAciesPMA.
//

namespace BeneficialStrategies.Iso20022.Choices.ClearingSystemMemberIdentification4Choice;

/// <summary>
/// Italian Domestic Identification Code - identifies Italian financial institutions on the Italian national clearing system. The code is assigned by the Associazione Bancaria Italiana (ABI).
/// </summary>
public partial record ItalianDomesticIdentificationCode : IClearingSystemMemberIdentification4Choice
{
    // Members coming soon...
}
