//
// GENERATED CODE, DO NOT EDIT THIS FILE!
//
// Generated by ConcreteChoiceGenerator for ProcessedStatus.  ISO2002 ID# _RiYWwdp-Ed-ak6NoX_4Aeg_-416590020.
//

namespace BeneficialStrategies.Iso20022.Choices.CorporateActionDeactivationCancellationStatus1Choice;

/// <summary>
/// Provides information about the processing status of the cancellation request.
/// </summary>
public partial record ProcessedStatus : ICorporateActionDeactivationCancellationStatus1Choice
{
    // Members coming soon...
}
