//
// GENERATED CODE, DO NOT EDIT THIS FILE!
//
// Generated by ConcreteChoiceGenerator for AcknowledgedAccepted.  ISO2002 ID# _4BPm8_8dEeCrw_OT0uBMXQ.
//

using BeneficialStrategies.Iso20022.Components;
using BeneficialStrategies.Iso20022.ExternalSchema;

namespace BeneficialStrategies.Iso20022.Choices.InstructionProcessingStatus10Choice;

/// <summary>
/// Instruction has been acknowledged by the account servicer.
/// </summary>
public partial record AcknowledgedAccepted : IInstructionProcessingStatus10Choice
{
    #nullable enable
    #nullable disable
}
