//
// GENERATED CODE, DO NOT EDIT THIS FILE!
//
// Generated by DropdownRowInterfaceGenerator for ActionType1Code.  ISO2002 ID# _TR6hggEcEeCQm6a_G2yO_w_-1866554273.
//

namespace BeneficialStrategies.Iso20022.Codesets;

/// <summary>
/// The values that should be expected from a single row of dropdown data.
/// </summary>
public partial interface IActionType1CodeDropdownRow : IEnumMetadataDropdownRow<ActionType1Code>
{
}

