//
// GENERATED CODE, DO NOT EDIT THIS FILE!
//
// Generated by DropdownSourceInterfaceGenerator for ATMCommand1Code.  ISO2002 ID# _FHH00IqKEeSRT5rEzcAHEw.
//

namespace BeneficialStrategies.Iso20022.Codesets;

/// <summary>
/// Used to inject dependencies that require dropdown choice values.
/// Understood to be uniquely a source of choices appropriate for a valid ATMCommand1Code value.
/// It is strongly urged that you use the provided <seealso cref="ATMCommand1CodeDropdownSource"/> that extracts the ISO20022 specified values from metadata in the codebase.
/// </summary>


public partial interface IATMCommand1CodeDropdownSource : IDropdownDataSource<IATMCommand1CodeDropdownRow>
{
}

