//
// GENERATED CODE, DO NOT EDIT THIS FILE!
//
// Generated by DropdownRowInterfaceGenerator for BasisPriceTypeCode.  ISO2002 ID# _bdLL-dp-Ed-ak6NoX_4Aeg_335335188.
//

namespace BeneficialStrategies.Iso20222.Common;

/// <summary>
/// The values that should be expected from a single row of dropdown data.
/// </summary>
public partial interface IBasisPriceTypeCodeDropdownRow : IEnumMetadataDropdownRow<BasisPriceTypeCode>
{
}

