//
// GENERATED CODE, DO NOT EDIT THIS FILE!
//
// Generated by DropdownSourceInterfaceGenerator for BondType1Code.  ISO2002 ID# _d6LiAM4mEeSc85GUbgBycw.
//

namespace BeneficialStrategies.Iso20222.Common;

/// <summary>
/// Used to inject dependencies that require dropdown choice values.
/// Understood to be uniquely a source of choices appropriate for a valid BondType1Code value.
/// It is the responsibility of the implementers of this interface to conform to the required specifications.
/// </summary>


public partial interface IBondType1CodeDropdownSource : IDropdownDataSource<IBondType1CodeDropdownRow>
{
}

