//
// GENERATED CODE, DO NOT EDIT THIS FILE!
//
// Generated by DropdownRowInterfaceGenerator for CallInCode.  ISO2002 ID# _bXW30tp-Ed-ak6NoX_4Aeg_-343201614.
//

namespace BeneficialStrategies.Iso20022.Codesets;

/// <summary>
/// The values that should be expected from a single row of dropdown data.
/// </summary>
public partial interface ICallInCodeDropdownRow : IEnumMetadataDropdownRow<CallInCode>
{
}

