//
// GENERATED CODE, DO NOT EDIT THIS FILE!
//
// Generated by DropdownSourceInterfaceGenerator for CardDataReading1Code.  ISO2002 ID# _TSXNcQEcEeCQm6a_G2yO_w_2087394966.
//

namespace BeneficialStrategies.Iso20022.Codesets;

/// <summary>
/// Used to inject dependencies that require dropdown choice values.
/// Understood to be uniquely a source of choices appropriate for a valid CardDataReading1Code value.
/// It is strongly urged that you use the provided <seealso cref="CardDataReading1CodeDropdownSource"/> that extracts the ISO20022 specified values from metadata in the codebase.
/// </summary>


public partial interface ICardDataReading1CodeDropdownSource : IDropdownDataSource<ICardDataReading1CodeDropdownRow>
{
}

