//
// GENERATED CODE, DO NOT EDIT THIS FILE!
//
// Generated by DropdownSourceInterfaceGenerator for CashMarginOrderCode.  ISO2002 ID# _a7DWUNp-Ed-ak6NoX_4Aeg_335335634.
//

namespace BeneficialStrategies.Iso20022.Codesets;

/// <summary>
/// Used to inject dependencies that require dropdown choice values.
/// Understood to be uniquely a source of choices appropriate for a valid CashMarginOrderCode value.
/// It is strongly urged that you use the provided <seealso cref="CashMarginOrderCodeDropdownSource"/> that extracts the ISO20022 specified values from metadata in the codebase.
/// </summary>


public partial interface ICashMarginOrderCodeDropdownSource : IDropdownDataSource<ICashMarginOrderCodeDropdownRow>
{
}

