//
// GENERATED CODE, DO NOT EDIT THIS FILE!
//
// Generated by DropdownSourceInterfaceGenerator for ExternalUnitOfMeasureCode.  ISO2002 ID# _KGEoLzNmEe2UWZuK9pqFtg.
//

namespace BeneficialStrategies.Iso20222.Common;

/// <summary>
/// Used to inject dependencies that require dropdown choice values.
/// Understood to be uniquely a source of choices appropriate for a valid ExternalUnitOfMeasureCode value.
/// It is strongly urged that you use the provided <seealso cref="ExternalUnitOfMeasureCodeDropdownSource"/> that extracts the ISO20022 specified values from metadata in the codebase.
/// </summary>


public partial interface IExternalUnitOfMeasureCodeDropdownSource : IDropdownDataSource<IExternalUnitOfMeasureCodeDropdownRow>
{
}

