//
// GENERATED CODE, DO NOT EDIT THIS FILE!
//
// Generated by DropdownRowInterfaceGenerator for ExternalPaymentCancellationRejection1Code.  ISO2002 ID# _-LDBoIlyEeePr-EGJjGYzQ.
//

namespace BeneficialStrategies.Iso20222.Common;

/// <summary>
/// The values that should be expected from a single row of dropdown data.
/// </summary>
public partial interface IExternalPaymentCancellationRejection1CodeDropdownRow : IEnumMetadataDropdownRow<ExternalPaymentCancellationRejection1Code>
{
}

