//
// GENERATED CODE, DO NOT EDIT THIS FILE!
//
// Generated by DropdownSourceInterfaceGenerator for Frequency3Code.  ISO2002 ID# _Yajvh9p-Ed-ak6NoX_4Aeg_560112330.
//

namespace BeneficialStrategies.Iso20222.Common;

/// <summary>
/// Used to inject dependencies that require dropdown choice values.
/// Understood to be uniquely a source of choices appropriate for a valid Frequency3Code value.
/// It is the responsibility of the implementers of this interface to conform to the required specifications.
/// </summary>


public partial interface IFrequency3CodeDropdownSource : IDropdownDataSource<IFrequency3CodeDropdownRow>
{
}

