//
// GENERATED CODE, DO NOT EDIT THIS FILE!
//
// Generated by DropdownSourceInterfaceGenerator for InstructionReason3Code.  ISO2002 ID# _vPEjgA-xEeuE0Pnt-OcNOA.
//

namespace BeneficialStrategies.Iso20022.Codesets;

/// <summary>
/// Used to inject dependencies that require dropdown choice values.
/// Understood to be uniquely a source of choices appropriate for a valid InstructionReason3Code value.
/// It is strongly urged that you use the provided <seealso cref="InstructionReason3CodeDropdownSource"/> that extracts the ISO20022 specified values from metadata in the codebase.
/// </summary>


public partial interface IInstructionReason3CodeDropdownSource : IDropdownDataSource<IInstructionReason3CodeDropdownRow>
{
}

