//
// GENERATED CODE, DO NOT EDIT THIS FILE!
//
// Generated by DropdownRowInterfaceGenerator for MeetingDateStatusCode.  ISO2002 ID# _aVWBNtp-Ed-ak6NoX_4Aeg_-958051818.
//

namespace BeneficialStrategies.Iso20022.Codesets;

/// <summary>
/// The values that should be expected from a single row of dropdown data.
/// </summary>
public partial interface IMeetingDateStatusCodeDropdownRow : IEnumMetadataDropdownRow<MeetingDateStatusCode>
{
}

