//
// GENERATED CODE, DO NOT EDIT THIS FILE!
//
// Generated by DropdownRowInterfaceGenerator for ReportIndicator1Code.  ISO2002 ID# _ZTCPotp-Ed-ak6NoX_4Aeg_1670165238.
//

namespace BeneficialStrategies.Iso20022.Codesets;

/// <summary>
/// The values that should be expected from a single row of dropdown data.
/// </summary>
public partial interface IReportIndicator1CodeDropdownRow : IEnumMetadataDropdownRow<ReportIndicator1Code>
{
}

