//
// GENERATED CODE, DO NOT EDIT THIS FILE!
//
// Generated by DropdownRowInterfaceGenerator for SecuritiesTransactionType15Code.  ISO2002 ID# _NGryILu7EeSXxOgurgHGgw.
//

namespace BeneficialStrategies.Iso20222.Common;

/// <summary>
/// The values that should be expected from a single row of dropdown data.
/// </summary>
public partial interface ISecuritiesTransactionType15CodeDropdownRow : IEnumMetadataDropdownRow<SecuritiesTransactionType15Code>
{
}

