//
// GENERATED CODE, DO NOT EDIT THIS FILE!
//
// Generated by DropdownRowInterfaceGenerator for TradeConfirmationType1Code.  ISO2002 ID# _2EE7YA26EeWmAKKPnqYEVQ.
//

namespace BeneficialStrategies.Iso20022.Codesets;

/// <summary>
/// The values that should be expected from a single row of dropdown data.
/// </summary>
public partial interface ITradeConfirmationType1CodeDropdownRow : IEnumMetadataDropdownRow<TradeConfirmationType1Code>
{
}

