//
// GENERATED CODE, DO NOT EDIT THIS FILE!
//
// Generated by DropdownRowInterfaceGenerator for UnderlyingProductIdentifier1Code.  ISO2002 ID# _-ZqKICjmEeK1Sbo8NpBROA.
//

namespace BeneficialStrategies.Iso20022.Codesets;

/// <summary>
/// The values that should be expected from a single row of dropdown data.
/// </summary>
public partial interface IUnderlyingProductIdentifier1CodeDropdownRow : IEnumMetadataDropdownRow<UnderlyingProductIdentifier1Code>
{
}

