//
// GENERATED CODE, DO NOT EDIT THIS FILE!
//
// Generated by DropdownRowInterfaceGenerator for VotingParticipationMethodCode.  ISO2002 ID# _muenYK3wEemG7MmivSuE5g.
//

namespace BeneficialStrategies.Iso20222.Common;

/// <summary>
/// The values that should be expected from a single row of dropdown data.
/// </summary>
public partial interface IVotingParticipationMethodCodeDropdownRow : IEnumMetadataDropdownRow<VotingParticipationMethodCode>
{
}

